cat("=============================\n")
cat("Code for children in primary school age and secondary school age transfered from stata generated by Mark")

dat_all <- dat_all %>% mutate(
  primaryschoolage = case_when(
    country_iso3 == "caf" & schage >= 6 & schage <= 11 ~ 1,
    country_iso3 == "tcd" & schage >= 6 & schage <= 11 ~ 1,
    country_iso3 == "cod" & schage >= 6 & schage <= 11 ~ 1,
    country_iso3 == "gha" & schage >= 6 & schage <= 11 ~ 1,
    country_iso3 == "mdg" & schage >= 6 & schage <= 10 ~ 1,
    country_iso3 == "mwi" & schage >= 6 & schage <= 11 ~ 1,
    country_iso3 == "nga" & schage >= 6 & schage <= 11 ~ 1,
    country_iso3 == "sle" & schage >= 6 & schage <= 11 ~ 1,
    country_iso3 == "tgo" & schage >= 6 & schage <= 11 ~ 1,
    TRUE ~ NA_real_
  ),
  lowersecondaryschoolage = case_when(
    country_iso3 == "caf" & schage >= 12 & schage <= 14 ~ 1,
    country_iso3 == "tcd" & schage >= 12 & schage <= 14 ~ 1,
    country_iso3 == "cod" & schage >= 12 & schage <= 13 ~ 1,
    country_iso3 == "gha" & schage >= 12 & schage <= 14 ~ 1,
    country_iso3 == "mdg" & schage >= 11 & schage <= 14 ~ 1,
    country_iso3 == "mwi" & schage >= 12 & schage <= 15 ~ 1,
    country_iso3 == "nga" & schage >= 12 & schage <= 14 ~ 1,
    country_iso3 == "sle" & schage >= 12 & schage <= 14 ~ 1,
    country_iso3 == "tgo" & schage >= 12 & schage <= 15 ~ 1,
    TRUE ~ NA_real_
  )
)