cat("=============================\n")
cat("Code for overage transfered from stata generated by Mark")
# Across the 47 MICs countries, there are eight different primary school systems as per the ISCED/UN Stats dat_allbase.
# A primary school system can have a different entrance age and duration.
# The code below generates a variable to group children according to the primary school system of their country.
# Their age etc is irrelevant for now - it's just their country's system
dat_all <- dat_all %>%
  mutate(
    # For Type 1 (Entrance Age 6, Duration 5
    age_school_ISCED_Type1 = 
      if_else(Official_entrance_age_primary == 6 & Theoretical_duration_primar == 5, 1, NA_integer_),
    # For Type 2 (Entrance Age 6, Duration 6):
    age_school_ISCED_Type2 = 
      if_else(Official_entrance_age_primary == 6 & Theoretical_duration_primar == 6, 1, NA_integer_),
    # For Type 3 (Entrance Age 6, Duration 4):
    age_school_ISCED_Type3 = 
      if_else(Official_entrance_age_primary == 6 & Theoretical_duration_primar == 4, 1, NA_integer_),
    # For Type 4 (Entrance Age 7, Duration 6):
    age_school_ISCED_Type4 = 
      if_else(Official_entrance_age_primary == 7 & Theoretical_duration_primar == 6, 1, NA_integer_),
    # For Type 5 (Entrance Age 7, Duration 4):
    age_school_ISCED_Type5 = 
      if_else(Official_entrance_age_primary == 7 & Theoretical_duration_primar == 4, 1, NA_integer_),
    # For Type 6 (Entrance Age 6, Duration 7):
    age_school_ISCED_Type6 = 
      if_else(Official_entrance_age_primary == 6 & Theoretical_duration_primar == 7, 1, NA_integer_),
    # For Type 7 (Entrance Age 5, Duration 5):
    age_school_ISCED_Type7 = 
      if_else(Official_entrance_age_primary == 5 & Theoretical_duration_primar == 5, 1, NA_integer_),
    # For Type 8 (Entrance Age 5, Duration 6):
    age_school_ISCED_Type8 = 
      if_else(Official_entrance_age_primary == 5 & Theoretical_duration_primar == 6, 1, NA_integer_)
  )

# Cleaning up ED10A. Most countries measure early childhood as 0 and primary as 1.
# Reclassify countries that deviate from this scheme so that 1 = Primary, 0 = ECD in all cases.
# Nepal also includes non-attenders in this measure. They are classified as missing.

dat_all <- dat_all %>%
  mutate(
    school_level = ED10A,
    # Create a backup variable
    school_level2 = school_level
  ) %>%
  mutate(
    # DRC and Chad use 10 for Primary; Nigeria and Turks and Caicos use 11.
    school_level = case_when(
      country_iso3 %in% c("tcd", "cod") & school_level == 10 ~ 1,
      country_iso3 %in% c("nga", "tca") & school_level == 11 ~ 1,
      TRUE ~ school_level
    )
  )

# Dummy grade variable
dat_all <- dat_all %>%
  mutate(grade = ED10B, 
         # Create a backup variable
         grade2 = grade)


# Labeling gender
dat_all$gender <- dat_all$HL4
levels(dat_all$gender) <- c("Male", "Female")

# Recode 5 cases where 3 was measured in a country
dat_all$gender[dat_all$gender == 3] <- NA


# There is still the issue that the grade variable is sometimes messy.
# Algeria (Entrance Age 6, Duration 5) has 29 cases at primary in grade 6,
# even though there are supposed to be five classes.
# Also, some countries' "primary schools" may last longer than what is internationally considered primary.
dat_all <- dat_all %>% mutate(
  grade = case_when(
    # Type 1, Type 7 Duration 5
    (age_school_ISCED_Type1 == 1 | age_school_ISCED_Type7 == 1) & grade2 >= 6 ~ NA_integer_,
    # Type 2, Type 4, Type 8 Duration 6
    (age_school_ISCED_Type2 == 1 | age_school_ISCED_Type4 == 1 | age_school_ISCED_Type8 == 1) & grade2 >= 7 ~ NA_integer_,
    # Type 3, Type 5 Duration 4
    (age_school_ISCED_Type3 == 1 | age_school_ISCED_Type5 == 1) & grade2 >= 5 ~ NA_integer_,
    # Type 6
    age_school_ISCED_Type6 == 1 & grade2 >= 8 ~ NA_integer_,
    TRUE ~ grade
  )
)

# Disability
#dat_all$disability <- factor(dat_all$disability, labels = c("non-disabled", "disabled"))

# In Malawi, international ISCED definition of lower secondary is different from national.
# Recode grade2 for lower secondary analysis
dat_all <- dat_all %>%
  mutate(
    grade2 = ifelse(ED10B == 98 & country_iso3 == "mwi", NA_integer_, grade2)
  ) %>%
  mutate(
    school_level = case_when(
      country_iso3 == "mwi" & grade2 %in% c(7, 8) ~ 2,
      TRUE ~ school_level
    )
  ) %>%
  mutate(
    grade2 = case_when(
      country_iso3 == "mwi" & school_level == 2 & grade2 == 1 ~ 3,
      country_iso3 == "mwi" & school_level == 2 & grade2 == 2 ~ 4,
      country_iso3 == "mwi" & school_level == 2 & grade2 == 7 ~ 1,
      country_iso3 == "mwi" & school_level == 2 & grade2 == 8 ~ 2,
      TRUE ~ grade2
    )
  )


# Identifies all children attending primary school
# This code identifies all children of primary school age

dat_all <- dat_all %>% mutate(
  ageForGrade = NA,
  ageForGrade = case_when(
    age_school_ISCED_Type1 == 1 ~ 6 + grade - 1,
    age_school_ISCED_Type2 == 1 ~ 6 + grade - 1,
    age_school_ISCED_Type3 == 1 ~ 6 + grade - 1,
    age_school_ISCED_Type4 == 1 ~ 7 + grade - 1,
    age_school_ISCED_Type5 == 1 ~ 7 + grade - 1,
    age_school_ISCED_Type6 == 1 ~ 6 + grade - 1,
    age_school_ISCED_Type7 == 1 ~ 5 + grade - 1,
    age_school_ISCED_Type8 == 1 ~ 5 + grade - 1,
    TRUE ~ NA_integer_
  ))

# Remove responses for kids of primary school age not actually attending primary school
dat_all <- dat_all %>%
  mutate(
    ageForGrade = if_else(school_level != 1, NA_integer_, ageForGrade),
    ageP = NA, 
    ageP = case_when(
      schage < ageForGrade ~ 1,
      schage == ageForGrade ~ 2,
      schage == ageForGrade + 1 ~ 3,
      schage > ageForGrade + 1 ~ 4,
      school_level != 1 ~ NA_integer_
    )
  )

# Convert age to binary DV overage
dat_all <- dat_all %>%
  mutate(overage_P = case_when(
   ageP %in% c(1, 2, 3) ~ 0,
   ageP == 4 ~ 1,
   is.na(ageP) ~ NA
  ))

# Label variable overage
dat_all <- dat_all %>% mutate(
  overage_P = factor(overage_P, levels = c(0:1), labels = c("Not overage", "Overage for grade primary")))

# Label variable ageP
dat_all <- dat_all %>% mutate(
  ageP = factor(ageP, levels = c(1:4), labels = c("Under-age", "At official age", "Over-age by 1 year", "Over-age by 2 or more [1]"))
)

# Cleaning for lower secondary analysis
dat_all <- dat_all %>%
  mutate(
    school_level = case_when(
      country_iso3 == "tcd" & school_level %in% c(20, 21) ~ 2,
      country_iso3 == "cod" & school_level == 20 ~ 2,
      country_iso3 == "gha" & school_level == 3 ~ 2,
      country_iso3 == "nga" & school_level %in% c(20, 21) ~ 2,
      TRUE ~ school_level
    )
  ) %>%
  mutate(
    ageForGrade_LS = case_when(
      country_iso3 == "caf" & school_level == 2 ~ 12 + grade - 1,
      country_iso3 == "tcd" & school_level == 2 ~ 12 + grade - 1,
      country_iso3 == "cod" & school_level == 2 ~ 12 + grade - 1,
      country_iso3 == "gha" & school_level == 2 ~ 12 + grade - 1,
      country_iso3 == "nga" & school_level == 2 ~ 12 + grade - 1,
      country_iso3 == "sle" & school_level == 2 ~ 12 + grade - 1,
      country_iso3 == "tgo" & school_level == 2 ~ 12 + grade - 1,
      
      country_iso3 == "mwi" & school_level == 2 ~ 12 + grade2 - 1,
      country_iso3 == "mdg" & school_level == 2 ~ 11 + grade - 1,
      TRUE ~ NA_integer_
    )) 

dat_all$age_LS <- 0
dat_all <- dat_all %>%
  mutate(
    age_LS = case_when(
      schage < ageForGrade_LS ~ 1,
      schage == ageForGrade_LS ~ 2,
      schage == ageForGrade_LS + 1 ~ 3,
      schage > ageForGrade_LS + 1 ~ 4,
      school_level != 2 ~ NA_integer_
    )
  ) 


#Coverting age_LS to binary DV overage_LS which is the key DV for lower secondary school analysis  
dat_all <- dat_all %>% 
  mutate(overage_LS = case_when(
    age_LS %in% c(1, 2, 3) ~ 0,
    age_LS == 4 ~ 1,
    is.na(age_LS) ~ NA)) %>% 
  mutate(overage_LS = factor(overage_LS, levels = c(0:1), 
                             labels = c("Not overage", "Overage for grade lower secondary")))

# Label variable age_LS
dat_all <- dat_all %>% mutate(
  age_LS = factor(age_LS, levels = c(1:4), 
                  labels = c("Under-age", "At official age", "Over-age by 1 year", "Over-age by 2 or more [1]"))
)








